name: Greeting Workflow

on:
  push:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Greet the User
        run: echo "Hello, ${{ github.actor }}! Thank you for your contribution."
